graph TD

%% --- CORE ---
    subgraph skysync-core
        FlightEvent((FlightEvent))
        WeatherEvent((WeatherEvent))
        Vuelo(Vuelo)
        Clima(Clima)

        VueloRepository[[<<interface>> VueloRepository]]
        ClimaRepository[[<<interface>> ClimaRepository]]
        ClimaPorCodigoPort[[<<interface>> ClimaPorCodigoPort]]
        PredecirCancelacionUseCase[[<<interface>> PredecirCancelacionUseCase]]

        VueloRepository -->|manages| Vuelo
        ClimaRepository -->|manages| Clima
        ClimaPorCodigoPort -->|queries| Clima
        PredecirCancelacionUseCase -->|uses| Vuelo
        PredecirCancelacionUseCase -->|uses| Clima
    end

%% --- BROKER ---
    subgraph ActiveMQ
        Broker((Broker))
    end

%% --- FEEDERS ---
    subgraph skysync-feeder-weather
        WeatherPublisher(WeatherPublisher)
        WeatherPublisher -->|publishes to| Broker
    end

    subgraph skysync-feeder-flights
        FlightPublisher(FlightPublisher)
        FlightPublisher -->|publishes to| Broker
    end

%% --- EVENT STORE BUILDER ---
    subgraph skysync-event-store-builder
        EventStoreBrokerAdapter(EventStoreBrokerAdapter)
        Broker -->|consumes from| EventStoreBrokerAdapter
    end

%% --- BUSINESS UNIT ---
    subgraph skysync-business-unit
        SkySyncRestServer(SkySyncRestServer)
        SkySync(SkySync)
        BusinessUnitEventAdapter(BusinessUnitEventAdapter)
        SQLiteClimaRepository(SQLiteClimaRepository)
        SQLiteVueloRepository(SQLiteVueloRepository)
        PredecirCancelacionService(PredecirCancelacionService)
        GenerarInformeService(GenerarInformeService)

        SkySyncRestServer -->|uses| BusinessUnitEventAdapter
        SkySync -->|uses| BusinessUnitEventAdapter

        BusinessUnitEventAdapter -->|accesses| SQLiteClimaRepository
        BusinessUnitEventAdapter -->|accesses| SQLiteVueloRepository

        BusinessUnitEventAdapter -->|delegates to| PredecirCancelacionService
        BusinessUnitEventAdapter -->|delegates to| GenerarInformeService

        SQLiteClimaRepository -->|implements| ClimaRepository
        SQLiteVueloRepository -->|implements| VueloRepository
        PredecirCancelacionService -->|implements| PredecirCancelacionUseCase
        GenerarInformeService -->|implements| GenerarInformeUseCase

        Broker -->|consumes from| BusinessUnitEventAdapter
    end
